export type CreationAction =
  | 'boost'
  | 'stop'
  | 'recover'
  | 'ram'
  | 'back-up'
  | 'chase'
  | 'avoid-wall'
  | 'aim'
  | 'bite'
  | 'claw-rake'
  | 'wing-buffet'
  | 'tail-sweep'
  | 'horn-charge'
  | 'fire-breath'
  | 'guard'
  | 'dodge';
