import {
  DragonAssignment,
  DragonSimulationDefinition,
  DragonSimulationId,
  InstructionLevel,
  InstructionLevelProfile,
  INSTRUCTION_LEVEL_LABELS,
  LevelChallenge,
  SimulationSectionDefinition,
} from './dragon-simulation.models';
import { ALLELE_VAULT_GENES } from '../workstations/allele-workbench/allele-vault.models';
import { DEFAULT_DRAGON_CLASS_JOURNEY_PLAN } from '../journey/config/dragon-journey.registry';
import { DEFAULT_INQUIRY_SETTINGS } from '../inquiry/inquiry-policy';

/**
 * Bumped to 2 when questions moved to the inquiry bank. Runs recorded before that carry no
 * `servedItemIds`, so they cannot be rebuilt and are regenerated instead of rendering empty.
 */
export const DRAGON_SIMULATION_CONTENT_VERSION = 2;

export const LEVEL_PROFILES: Record<InstructionLevel, InstructionLevelProfile> = {
  'grade-7': {
    id: 'grade-7',
    label: INSTRUCTION_LEVEL_LABELS['grade-7'],
    shortLabel: 'G7',
    questionCount: 3,
    scaffold: 'high',
    hintsAllowed: true,
    reasoningLabel: 'Identify and connect visible evidence',
  },
  'grade-8': {
    id: 'grade-8',
    label: INSTRUCTION_LEVEL_LABELS['grade-8'],
    shortLabel: 'G8',
    questionCount: 3,
    scaffold: 'medium',
    hintsAllowed: true,
    reasoningLabel: 'Use genotype notation and ratios',
  },
  'high-school': {
    id: 'high-school',
    label: INSTRUCTION_LEVEL_LABELS['high-school'],
    shortLabel: 'HS',
    questionCount: 4,
    scaffold: 'low',
    hintsAllowed: false,
    reasoningLabel: 'Build multi-step probability arguments',
  },
  'ap-biology': {
    id: 'ap-biology',
    label: INSTRUCTION_LEVEL_LABELS['ap-biology'],
    shortLabel: 'AP',
    questionCount: 5,
    scaffold: 'none',
    hintsAllowed: false,
    reasoningLabel: 'Evaluate data, assumptions, and model limitations',
  },
};

const SECTIONS: readonly SimulationSectionDefinition[] = [
  {
    id: 'observe',
    phase: 'observe',
    title: 'Inspect the system',
    cue: 'Open the evidence before making a claim.',
  },
  {
    id: 'predict',
    phase: 'predict',
    title: 'Lock a prediction',
    cue: 'Commit before the model reveals its result.',
  },
  {
    id: 'manipulate',
    phase: 'manipulate',
    title: 'Operate the model',
    cue: 'Change or trace one meaningful part.',
  },
  {
    id: 'explain',
    phase: 'explain',
    title: 'Defend with evidence',
    cue: 'Select the evidence that actually supports the claim.',
  },
];

function challenge(
  prompt: string,
  options: readonly [string, string, string],
  correctIndex: 0 | 1 | 2,
  explanation: string,
  misconceptionFlag: string,
  focusNodeId?: string,
): LevelChallenge {
  const ids = ['a', 'b', 'c'] as const;
  return {
    prompt,
    options: options.map((label, index) => ({ id: ids[index], label })),
    correctOptionId: ids[correctIndex],
    explanation,
    misconceptionFlag,
    focusNodeId,
  };
}

const DRAGON_SIMULATION_CATALOG: readonly DragonSimulationDefinition[] = [
  {
    id: 'trait-evidence',
    module: 1,
    title: 'Trait Evidence Analyzer',
    shortTitle: 'Trait evidence',
    skill: 'GEN-1',
    goal: 'Use dragon anatomy, reflex trials, command trials, and records to distinguish inherited, innate, and learned characteristics.',
    visualKind: 'evidence',
    accent: '#ff8f70',
    sections: SECTIONS,
    nodes: [
      {
        id: 'appearance',
        label: 'Fighting anatomy',
        detail: 'Horns, wings, fire ability, and tail structure.',
        symbol: '◉',
      },
      {
        id: 'hatch-record',
        label: 'Hatch record',
        detail: 'A characteristic recorded before training.',
        symbol: 'DNA',
      },
      {
        id: 'training-log',
        label: 'Command training',
        detail: 'A response practiced during life.',
        symbol: '↗',
      },
      {
        id: 'reflex-trial',
        label: 'Reflex trial',
        detail: 'An automatic protective response to a flame flash.',
        symbol: '☁',
      },
    ],
    levelChallenges: {
      'grade-7': challenge(
        'Which record best supports the claim that horn structure is inherited?',
        [
          'A hatch record and matching family pattern',
          'A successful horn charge today',
          'A trainer calling the guard command',
        ],
        0,
        'A characteristic present at hatching and patterned in a family supports inheritance.',
        'appearance-as-proof',
        'hatch-record',
      ),
      'grade-8': challenge(
        'A dragon begins guarding only after repeated command practice. How should the response be classified?',
        ['Inherited anatomy', 'Learned command response', 'Innate reflex'],
        1,
        'A response acquired through command practice is learned.',
        'learned-is-genetic',
        'training-log',
      ),
      'high-school': challenge(
        'Untrained hatchlings close their eyes and nostrils during a flame flash. Which category best fits?',
        ['Learned command', 'Innate protective reflex', 'Tail anatomy'],
        1,
        'A repeatable automatic response present before training is an innate reflex.',
        'reflex-is-trained',
        'reflex-trial',
      ),
      'ap-biology': challenge(
        'Which comparison best separates an innate reflex from a learned command response?',
        [
          'Run both responses only after training',
          'Compare pre-training flame-flash trials with command-training records',
          'Compare which response looks more dramatic',
        ],
        1,
        'Pre-training reflex trials and training records distinguish automatic responses from learned cues.',
        'correlation-as-causation',
        'reflex-trial',
      ),
    },
  },
  {
    id: 'genome-microscope',
    module: 2,
    title: 'Genome Microscope',
    shortTitle: 'Genome microscope',
    skill: 'GEN-2',
    goal: 'Travel from organism to chromosome, DNA, gene, and allele without collapsing the hierarchy.',
    visualKind: 'microscope',
    accent: '#65c8bc',
    sections: SECTIONS,
    nodes: [
      { id: 'cell', label: 'Cell', detail: 'Contains the nucleus and chromosomes.', symbol: '○' },
      {
        id: 'chromosome',
        label: 'Chromosome',
        detail: 'A packaged DNA molecule containing many genes.',
        symbol: 'X',
      },
      { id: 'gene', label: 'Gene', detail: 'A section of DNA.', symbol: '▤' },
      { id: 'allele', label: 'Allele', detail: 'One version of a gene.', symbol: 'W' },
    ],
    levelChallenges: {
      'grade-7': challenge(
        'Which object contains many genes?',
        ['Chromosome', 'Visible trait', 'Allele'],
        0,
        'A chromosome is packaged DNA containing many genes.',
        'hierarchy-confusion',
        'chromosome',
      ),
      'grade-8': challenge(
        'W and w are different versions of the same wings gene. What are they?',
        ['Cells', 'Alleles', 'Chromosomes'],
        1,
        'Alleles are versions of a gene.',
        'allele-definition',
        'allele',
      ),
      'high-school': challenge(
        'Where should a regulatory sequence associated with a gene be placed in this model?',
        ['Within DNA near the gene', 'Outside the cell', 'As a phenotype'],
        0,
        'Regulatory sequences are DNA and can influence gene expression.',
        'dna-structure-confusion',
        'gene',
      ),
      'ap-biology': challenge(
        'Which limitation matters most when this model zooms directly from gene to phenotype?',
        [
          'It omits transcriptional regulation and environment',
          'Chromosomes contain DNA',
          'Alleles are gene variants',
        ],
        0,
        'Phenotype often depends on regulation, interactions, development, and environment.',
        'one-gene-one-trait',
        'gene',
      ),
    },
  },
  {
    id: 'allele-workbench',
    module: 4,
    title: 'Allele Workbench',
    shortTitle: 'Allele workbench',
    skill: 'GEN-4',
    goal: 'Change an allele, predict expression, and keep both alleles visible in the model.',
    visualKind: 'chromosome',
    accent: '#ad8bd2',
    sections: SECTIONS,
    nodes: [
      { id: 'slot-a', label: 'Chromosome A', detail: 'First allele socket.', symbol: 'W' },
      { id: 'slot-b', label: 'Chromosome B', detail: 'Second allele socket.', symbol: 'w' },
      {
        id: 'expression',
        label: 'Expression path',
        detail: 'The model applies its allele rule.',
        symbol: '→',
      },
      {
        id: 'carrier',
        label: 'Carrier state',
        detail: 'A recessive allele remains present.',
        symbol: 'Ww',
      },
    ],
    levelChallenges: {
      'grade-7': challenge(
        'If W is dominant, which pair shows the winged phenotype?',
        ['ww only', 'Ww', 'No pair'],
        1,
        'One W produces the modeled dominant phenotype.',
        'dominant-means-two',
        'expression',
      ),
      'grade-8': challenge(
        'What changes when Ww becomes ww?',
        ['One allele and the phenotype', 'The entire chromosome count', 'The parent source'],
        0,
        'Replacing W with w changes the pair and modeled expression.',
        'allele-chromosome-swap',
        'slot-a',
      ),
      'high-school': challenge(
        'Why must Ww still display both allele tokens after expression?',
        [
          'Expression does not delete the recessive allele',
          'w changes into W',
          'Only phenotype matters',
        ],
        0,
        'Dominance describes expression, not removal of an allele.',
        'recessive-disappears',
        'carrier',
      ),
      'ap-biology': challenge(
        'Which statement is a limitation of this workbench model?',
        [
          'It assumes simple complete dominance',
          'Diploid organisms have allele pairs',
          'Alleles occupy gene loci',
        ],
        0,
        'Many traits involve incomplete dominance, codominance, interactions, or environment.',
        'model-is-universal',
        'expression',
      ),
    },
  },
  {
    id: 'punnett-composer',
    module: 5,
    title: 'Punnett Composer',
    shortTitle: 'Punnett composer',
    skill: 'GEN-5',
    goal: 'Determine how one allele from each parent shapes possible offspring genotypes and probabilities.',
    visualKind: 'punnett',
    accent: '#5eb5e8',
    sections: SECTIONS,
    nodes: [
      {
        id: 'parent-a',
        label: 'Parent A gametes',
        detail: 'One allele enters each column.',
        symbol: 'A',
      },
      {
        id: 'parent-b',
        label: 'Parent B gametes',
        detail: 'One allele enters each row.',
        symbol: 'B',
      },
      {
        id: 'cells',
        label: 'Four combinations',
        detail: 'Each cell receives one allele from each parent.',
        symbol: '▦',
      },
      {
        id: 'probability',
        label: 'Predicted ratio',
        detail: 'Counts are converted to probability.',
        symbol: '%',
      },
    ],
    levelChallenges: {
      'grade-7': challenge(
        'How many alleles belong in each offspring cell?',
        ['One total', 'One from each parent', 'Four from each parent'],
        1,
        'A diploid offspring receives one modeled allele from each parent.',
        'two-from-one-parent',
        'cells',
      ),
      'grade-8': challenge(
        'For Ww × ww, what fraction of cells are Ww?',
        ['1/4', '1/2', 'All'],
        1,
        'Two of four equally likely cells are Ww.',
        'punnett-count-error',
        'probability',
      ),
      'high-school': challenge(
        'For Ww × Ww, what is the expected recessive phenotype probability?',
        ['25%', '50%', '75%'],
        0,
        'Only ww, one of four cells, has the recessive phenotype.',
        'genotype-phenotype-ratio',
        'probability',
      ),
      'ap-biology': challenge(
        'What assumption makes the four Punnett cells equally likely?',
        [
          'Equal segregation and random fertilization',
          'Dominant alleles are more common',
          'Every family has four offspring',
        ],
        0,
        'The model assumes equal gamete probabilities and random combination.',
        'grid-equals-family',
        'cells',
      ),
    },
  },
  {
    id: 'incubator-sampler',
    module: 6,
    title: 'Incubator Sampler',
    shortTitle: 'Incubator sampler',
    skill: 'GEN-7',
    goal: 'Investigate how visible inherited traits appear and change across offspring and generations.',
    visualKind: 'sampler',
    accent: '#f29b56',
    sections: SECTIONS,
    nodes: [
      {
        id: 'parents',
        label: 'Parents',
        detail: 'Two dragons and the visible traits they show.',
        symbol: '2',
      },
      {
        id: 'batch',
        label: 'Offspring batch',
        detail: 'A freely chosen number of hatchlings sorted by one visible trait.',
        symbol: '◎',
      },
      {
        id: 'buckets',
        label: 'Phenotype buckets',
        detail: 'Visible outcome groups that can supply the next parents.',
        symbol: '▥',
      },
      { id: 'history', label: 'Generations', detail: 'A record of visible outcomes.', symbol: 'G' },
    ],
    levelChallenges: {
      'grade-7': challenge(
        'Which record best supports a claim about the most common visible form?',
        ['One parent name', 'Counts from several offspring batches', 'The incubator color'],
        1,
        'Repeated offspring counts provide stronger visible evidence than one specimen.',
        'probability-guarantee',
        'history',
      ),
      'grade-8': challenge(
        'What is the clearest way to compare a small batch with a large batch?',
        ['Compare visible-form percentages', 'Compare egg order', 'Use different traits'],
        0,
        'Percentages put differently sized visible-outcome batches on the same scale.',
        'sample-size-irrelevant',
        'batch',
      ),
      'high-school': challenge(
        'What observation shows that a visible form became more common after rebreeding?',
        ['Its percentage rises next generation', 'The batch runs faster', 'Parents have new names'],
        0,
        'A higher next-generation percentage directly shows a frequency change.',
        'percent-difference-error',
        'history',
      ),
      'ap-biology': challenge(
        'Which evidence best describes change across a phenotype-selected lineage?',
        [
          'Visible-form frequencies across generations',
          'One hatchling portrait',
          'Incubator temperature',
        ],
        0,
        'A generation series shows how the observed phenotype distribution changes over time.',
        'no-statistical-test',
        'history',
      ),
    },
  },
  {
    id: 'dna-process-lab',
    module: 8,
    title: 'DNA Replication, Mutation, and Repair Lab',
    shortTitle: 'DNA process lab',
    skill: 'GEN-2',
    goal: 'Determine how two DNA records differ, how mutations change those differences, and whether a selected repair restores sequence agreement.',
    visualKind: 'dna-process',
    accent: '#5d8ff1',
    sections: SECTIONS,
    nodes: [
      {
        id: 'replication',
        label: 'DNA replication',
        detail: 'Original strands guide new complementary DNA strands.',
        symbol: 'DNA',
      },
      {
        id: 'transcription',
        label: 'RNA transcription',
        detail: 'RNA polymerase builds an mRNA copy from a DNA template.',
        symbol: 'RNA',
      },
      {
        id: 'mutation',
        label: 'Mutation comparison',
        detail: 'Insertion, deletion, and substitution change sequences differently.',
        symbol: 'Δ',
      },
      {
        id: 'repair',
        label: 'DNA repair',
        detail: 'Pairing evidence guides correction of a copying mismatch.',
        symbol: '✓',
      },
    ],
    levelChallenges: {
      'grade-7': challenge(
        'What does each original DNA strand do during replication?',
        [
          'Acts as a template for a matching complementary strand',
          'Changes into RNA',
          'Disappears after copying',
        ],
        0,
        'Each original strand guides construction of a new complementary DNA strand.',
        'replication-destroys-template',
        'replication',
      ),
      'grade-8': challenge(
        'Why can U appear in an RNA transcript when it is not present in DNA?',
        ['RNA uses uracil in place of thymine', 'U marks every mutation', 'U repairs DNA'],
        0,
        'RNA contains uracil, so A in the DNA template pairs with U in the RNA transcript.',
        'rna-uses-thymine',
        'transcription',
      ),
      'high-school': challenge(
        'Which mutation changes one base pair without changing sequence length?',
        ['Substitution', 'Insertion', 'Deletion'],
        0,
        'A substitution exchanges one pair; insertions and deletions change sequence length.',
        'mutation-types-confused',
        'mutation',
      ),
      'ap-biology': challenge(
        'Why can mismatch repair prevent a copying error from becoming fixed in a lineage?',
        [
          'It restores complementary pairing before later rounds copy the change',
          'It converts the damaged DNA into RNA',
          'It guarantees that no mutation can ever persist',
        ],
        0,
        'Repair can replace a mismatched base before subsequent replication preserves the sequence change.',
        'repair-guarantees-no-mutations',
        'repair',
      ),
    },
  },
  {
    id: 'diversity-manager',
    module: 9,
    title: 'Diversity Manager',
    shortTitle: 'Diversity manager',
    skill: 'GEN-8',
    goal: 'Use allele frequency and genotype evidence to preserve population variation.',
    visualKind: 'population',
    accent: '#76a6e8',
    sections: SECTIONS,
    nodes: [
      {
        id: 'population',
        label: 'Starting population',
        detail: 'The same baseline is used for each strategy.',
        symbol: '●●●',
      },
      {
        id: 'narrow',
        label: 'Narrow strategy',
        detail: 'Repeatedly favors one visible phenotype.',
        symbol: '▼',
      },
      {
        id: 'balanced',
        label: 'Balanced strategy',
        detail: 'Retains more alleles and genotypes.',
        symbol: '◆',
      },
      {
        id: 'metrics',
        label: 'Diversity metrics',
        detail: 'Allele frequency and unique genotype counts.',
        symbol: '▥',
      },
    ],
    levelChallenges: {
      'grade-7': challenge(
        'Which strategy better preserves different alleles?',
        [
          'Use only one parent pair repeatedly',
          'Use a balanced set of carriers',
          'Choose the strongest-looking dragon',
        ],
        1,
        'A balanced breeding pool is more likely to retain different alleles.',
        'phenotype-equals-diversity',
        'balanced',
      ),
      'grade-8': challenge(
        'Which metric directly shows that an allele was lost?',
        ['Allele frequency reaches zero', 'Average body size rises', 'Battle score changes'],
        0,
        'A zero allele frequency means the modeled population no longer contains it.',
        'wrong-diversity-metric',
        'metrics',
      ),
      'high-school': challenge(
        'Why compare strategies from the same starting population and seed?',
        [
          'To isolate strategy effects',
          'To guarantee identical offspring',
          'To favor dominant alleles',
        ],
        0,
        'Equivalent starting conditions make the strategy comparison interpretable.',
        'confounded-comparison',
        'population',
      ),
      'ap-biology': challenge(
        'A rare recessive allele remains mostly in heterozygotes. Which metric must be tracked?',
        [
          'Allele frequency, not phenotype frequency alone',
          'Battle wins',
          'Only homozygous recessive count',
        ],
        0,
        'A recessive allele can persist while hidden in heterozygotes.',
        'phenotype-frequency-equals-allele',
        'metrics',
      ),
    },
  },
  {
    id: 'dragon-hatchery',
    module: 11,
    title: 'Dragon Hatchery',
    shortTitle: 'Gamete hatchery',
    skill: 'GEN-3',
    goal: 'Observe meiosis, choose one egg and one sperm, and inspect the paired chromosomes that form a fertilized egg.',
    visualKind: 'hatchery',
    accent: '#e7bd69',
    sections: SECTIONS,
    nodes: [
      {
        id: 'meiosis',
        label: 'Meiosis',
        detail: 'Each parent forms four genetically distinct haploid gametes.',
        symbol: '◯',
      },
      {
        id: 'egg-gamete',
        label: 'Egg gamete',
        detail: 'Carries one chromosome from each homologous pair.',
        symbol: '◉',
      },
      {
        id: 'sperm-gamete',
        label: 'Sperm gamete',
        detail: 'Carries a second haploid chromosome set.',
        symbol: 'DNA',
      },
      {
        id: 'fertilized-egg',
        label: 'Fertilized egg',
        detail: 'The two gamete nuclei combine to restore homologous chromosome pairs.',
        symbol: '◇',
      },
    ],
    levelChallenges: {
      'grade-7': challenge(
        'What restores a chromosome pair in the fertilized egg?',
        ['One chromosome from each gamete', 'Two from the egg', 'One made by the shell'],
        0,
        'The fertilized egg receives one homolog from the egg and one from the sperm.',
        'two-from-one-parent',
        'fertilized-egg',
      ),
      'grade-8': challenge(
        'Why does each gamete show only one chromosome of each type?',
        [
          'Meiosis halves the chromosome number',
          'Fertilization removes one',
          'The shell hides one',
        ],
        0,
        'Meiosis separates homologous pairs so each gamete is haploid.',
        'gamete-stays-diploid',
        'meiosis',
      ),
      'high-school': challenge(
        'What produces the two alleles shown at a fertilized-egg gene locus?',
        [
          'One inherited through each selected gamete',
          'Both copied from the egg gamete',
          'Both created during fertilization',
        ],
        0,
        'The paired locus records one allele from the egg and one from the sperm.',
        'two-from-one-parent',
        'fertilized-egg',
      ),
      'ap-biology': challenge(
        'Why can four gametes from one meiosis carry different allele combinations?',
        [
          'Independent assortment and crossing over',
          'Fertilization changes them',
          'Dominant alleles divide first',
        ],
        0,
        'Independent assortment and crossing over can create distinct haploid chromosome sets.',
        'identical-gametes',
        'meiosis',
      ),
    },
  },
  {
    id: 'dragon-arena',
    module: 12,
    title: 'Dragon Arena Combat',
    shortTitle: 'Arena evidence',
    skill: 'GEN-8',
    goal: 'Plan a fair combat trial and separate inherited traits from tactics, physics, and chance.',
    visualKind: 'arena',
    accent: '#ef745f',
    sections: SECTIONS,
    nodes: [
      {
        id: 'genetics',
        label: 'Inherited profile',
        detail: 'Modeled alleles influence selected physical properties.',
        symbol: 'DNA',
      },
      {
        id: 'strategy',
        label: 'Strategy program',
        detail: 'The same control rules make comparisons fairer.',
        symbol: '⌘',
      },
      {
        id: 'combat',
        label: 'Arena trial',
        detail: 'Physics and contact events produce the outcome.',
        symbol: '⚔',
      },
      {
        id: 'evidence',
        label: 'Outcome evidence',
        detail: 'The result is separated from the genetics claim.',
        symbol: '▤',
      },
    ],
    levelChallenges: {
      'grade-7': challenge(
        'A winged dragon wins. What can the trial prove by itself?',
        ['Wings caused the win', 'The dragon won this trial', 'Winged dragons always win'],
        1,
        'One trial records an outcome but does not isolate a single cause.',
        'outcome-as-cause',
        'evidence',
      ),
      'grade-8': challenge(
        'Which comparison is fairest for testing a trait effect?',
        [
          'Same strategy and arena conditions',
          'Different strategy for every dragon',
          'Choose only previous winners',
        ],
        0,
        'Holding strategy and conditions steady reduces confounding.',
        'unfair-comparison',
        'strategy',
      ),
      'high-school': challenge(
        'Why should battle score remain separate from genetics mastery?',
        [
          'Performance has multiple modeled causes',
          'Genotypes are not inherited',
          'Physics has no variation',
        ],
        0,
        'Strategy, contact physics, timing, and chance also influence performance.',
        'battle-equals-mastery',
        'combat',
      ),
      'ap-biology': challenge(
        'Which design best estimates an inherited-profile effect on damage?',
        [
          'Replicated trials with controlled strategy and randomized sides',
          'One champion trial',
          'Rank dragons by appearance',
        ],
        0,
        'Replication, controls, and randomization support a stronger causal inference.',
        'single-trial-causation',
        'genetics',
      ),
    },
  },
];

/** Dedicated open workstations are excluded from the checkpoint-style instrument deck. */
export const DRAGON_SIMULATIONS: readonly DragonSimulationDefinition[] =
  DRAGON_SIMULATION_CATALOG.filter((simulation) => simulation.id !== 'diversity-manager');

export const DRAGON_SIMULATION_BY_ID = Object.fromEntries(
  DRAGON_SIMULATIONS.map((simulation) => [simulation.id, simulation]),
) as Record<DragonSimulationId, DragonSimulationDefinition>;

export const DEFAULT_DRAGON_ASSIGNMENT: DragonAssignment = {
  id: 'default',
  ownerId: 'demo-teacher',
  classId: 'default',
  title: 'Dragon Genetics adaptive laboratory',
  defaultLevel: 'grade-7',
  alleleCatalog: {
    availableGeneIds: ALLELE_VAULT_GENES.map((gene) => gene.id),
  },
  simulationSettings: {},
  journeyPlan: DEFAULT_DRAGON_CLASS_JOURNEY_PLAN,
  inquirySettings: DEFAULT_INQUIRY_SETTINGS,
  studentOverrides: {},
  assignmentVersion: 5,
  updatedAtIso: new Date(0).toISOString(),
};

export function isDragonSimulationId(value: string | null): value is DragonSimulationId {
  return !!value && Object.prototype.hasOwnProperty.call(DRAGON_SIMULATION_BY_ID, value);
}
