import { ChoiceItem, ConceptId, InquiryItem } from './inquiry.models';
import { dragonConcept, DRAGON_CONCEPTS } from './concept.registry';
import { InstructionLevel, SimulationPhase } from '../adaptive/dragon-simulation.models';
import { ProbeId } from '../workstations/shared/instrument-manifest.models';
import { instrumentsWithProbe } from './instrument.registry';

/**
 * The authored inquiry bank.
 *
 * Items bind to a **concept** and a **probe**, never to a workstation id, so one item runs in every
 * instrument declaring that probe. Grade bands are an explicit set — an AP student never receives a
 * grade-7 item, and a grade-7 student never receives an AP one. Phase is authored rather than
 * derived from array position.
 *
 * Selection never pads a short bank with generated filler; a gap surfaces in the coverage report
 * instead. `assertValidInquiryBank()` keeps every item pointing at a real concept and a probe that
 * concept actually admits.
 */

const A: readonly InstructionLevel[] = ['grade-7', 'grade-8', 'high-school', 'ap-biology'];
const L: readonly InstructionLevel[] = ['grade-7', 'grade-8'];
const U: readonly InstructionLevel[] = ['grade-8', 'high-school', 'ap-biology'];
const X: readonly InstructionLevel[] = ['high-school', 'ap-biology'];
const G7: readonly InstructionLevel[] = ['grade-7'];

function c(
  id: string,
  conceptId: ConceptId,
  requiresProbe: ProbeId,
  gradeBands: readonly InstructionLevel[],
  phase: SimulationPhase,
  prompt: string,
  options: readonly [string, string, string],
  correctIndex: 0 | 1 | 2,
  explanation: string,
  hint?: string,
): ChoiceItem {
  const ids = ['a', 'b', 'c'] as const;
  return {
    kind: 'choice',
    id,
    conceptId,
    requiresProbe,
    gradeBands,
    phase,
    hint,
    source: 'registry',
    prompt,
    options: options.map((label, index) => ({ id: ids[index], label })),
    correctOptionId: ids[correctIndex],
    explanation,
  };
}

export const DRAGON_INQUIRY_BANK: readonly InquiryItem[] = [
  // ===== GEN-1 · inherited traits ==========================================
  c('gen1-learned-1', 'learned-is-genetic', 'trait.inherited-vs-acquired', A, 'explain',
    'A dragon was trained for months to fetch on command. Will its hatchlings be born knowing how to fetch?',
    ['No — a skill learned during life is not written into gametes', 'Yes — practice changes the genes it passes on', 'Only if both parents were trained the same way'],
    0,
    'Training changes an individual, not the alleles it passes to offspring.',
    'Ask what a hatchling could do before anyone taught it anything.'),
  c('gen1-learned-2', 'learned-is-genetic', 'trait.evidence-source', A, 'observe',
    'Which record best separates an inherited trait from a trained one?',
    ['The training log', 'The hatch record, taken before any training', 'The most recent trial score'],
    1,
    'A record made at hatching cannot contain anything the dragon later learned.',
    'Choose the record made earliest in the dragon’s life.'),
  c('gen1-learned-3', 'learned-is-genetic', 'trait.inherited-vs-acquired', L, 'manipulate',
    'Two siblings were raised apart. One was trained to glide further. What does the difference in gliding distance show?',
    ['That gliding distance is inherited', 'That the trained sibling has different alleles now', 'That the environment changed one sibling’s performance'],
    2,
    'Siblings raised differently show environmental effects, not a change in alleles.'),
  c('gen1-reflex-1', 'reflex-is-trained', 'trait.evidence-source', A, 'observe',
    'A hatchling snaps at a shadow seconds after emerging from the egg. What does that tell you?',
    ['The reflex is inherited, because there was no time to learn it', 'The reflex was learned inside the egg', 'Nothing — reflexes are always trained'],
    0,
    'A behaviour present before any experience is inherited, even though it looks like a skill.',
    'Consider how much time there was to practise.'),
  c('gen1-reflex-2', 'reflex-is-trained', 'trait.inherited-vs-acquired', U, 'explain',
    'A reflex trial and a training log disagree about the same dragon. Which supports an inheritance claim?',
    ['The training log, because it has more entries', 'The reflex trial, because it measures a response present without practice', 'Neither can support an inheritance claim'],
    1,
    'The reflex trial isolates what the dragon does without practice.'),
  c('gen1-appearance-1', 'appearance-as-proof', 'trait.observe', A, 'predict',
    'Two dragons both show flame breath. What can you conclude about their alleles?',
    ['They must carry identical allele pairs', 'They each carry at least one flame allele', 'They must both be carriers'],
    1,
    'The dominant form only proves at least one dominant allele; the second copy is unknown.',
    'One dominant allele is enough to show the form.'),
  c('gen1-appearance-2', 'appearance-as-proof', 'trait.evidence-source', A, 'explain',
    'Which evidence would settle whether two identical-looking dragons have the same genotype?',
    ['A side-by-side photograph', 'A DNA sample from each', 'A record of which one performs better'],
    1,
    'Only a genotype record names the alleles; appearance cannot.'),
  c('gen1-outcome-1', 'outcome-as-cause', 'trait.evidence-source', U, 'explain',
    'A dragon won a trial. Which claim does that result actually support?',
    ['Its wing alleles caused the win', 'This dragon out-performed this opponent on this day', 'Its whole breeding line is superior'],
    1,
    'A single outcome describes the event, not the cause behind it.'),
  c('gen1-outcome-2', 'outcome-as-cause', 'trial.outcome', X, 'explain',
    'To claim an inherited trait caused a trial result, what is the minimum you need?',
    ['One decisive win', 'Repeated trials across dragons that differ only in that trait', 'A larger arena'],
    1,
    'Attributing cause needs repetition and a controlled difference.'),
  c('gen1-correlation-1', 'correlation-as-causation', 'population.scan', X, 'explain',
    'In one island scan, long horns and heavy scales usually appear together. What follows?',
    ['Long horns cause heavy scales', 'The two traits are associated in this sample', 'The traits are on different chromosomes'],
    1,
    'An association in one sample is a pattern to explain, not a cause.'),

  // ===== GEN-2 · genome organization =======================================
  c('gen2-hierarchy-1', 'hierarchy-confusion', 'genome.hierarchy', A, 'observe',
    'Which object contains many genes?',
    ['A chromosome', 'An allele', 'A visible trait'],
    0,
    'A chromosome is one packaged DNA molecule carrying many genes along its length.',
    'Move outward from the gene until you reach the structure that holds many of them.'),
  c('gen2-hierarchy-2', 'hierarchy-confusion', 'genome.hierarchy', A, 'observe',
    'Put these in order from largest to smallest: gene, cell, chromosome, nucleus.',
    ['Cell, nucleus, chromosome, gene', 'Nucleus, cell, gene, chromosome', 'Chromosome, cell, nucleus, gene'],
    0,
    'The cell contains the nucleus, which holds chromosomes, each carrying many genes.'),
  c('gen2-hierarchy-3', 'hierarchy-confusion', 'gene.locus', L, 'manipulate',
    'You zoom to one chromosome and highlight a locus. What is highlighted?',
    ['One gene’s position on that chromosome', 'The entire chromosome', 'One cell'],
    0,
    'A locus is the address of one gene along the chromosome.'),
  c('gen2-swap-1', 'allele-chromosome-swap', 'chromosome.pair', A, 'observe',
    'Two homologous chromosomes are shown side by side. What is true of them?',
    ['They carry the same genes at the same positions', 'They carry completely different genes', 'One carries genes and the other does not'],
    0,
    'Homologs match gene-for-gene at matching loci; the alleles at those loci may differ.',
    'Compare the locus marks on both copies.'),
  c('gen2-swap-2', 'allele-chromosome-swap', 'allele.pair', A, 'explain',
    'A dragon carries a different allele on each homolog. What does that mean?',
    ['It has an extra chromosome', 'The two copies of one gene differ', 'The gene moved to another chromosome'],
    1,
    'Different alleles are different versions of the same gene at the same locus.'),
  c('gen2-chromatin-1', 'chromatin-is-separate', 'chromatin.packing', U, 'observe',
    'As you unpack a chromosome through chromatin fibres, what are you looking at?',
    ['A different molecule that surrounds the chromosome', 'The same DNA molecule at a looser packing level', 'A copy being made of the chromosome'],
    1,
    'Chromatin and chromosome are the same DNA at different degrees of folding.'),
  c('gen2-dna-1', 'dna-structure-confusion', 'dna.sequence', A, 'observe',
    'Where is the information stored in a DNA molecule?',
    ['In the order of its bases', 'In its colour', 'In how tightly it is coiled'],
    0,
    'The base order along the strand is what carries information.'),
  c('gen2-dna-2', 'dna-structure-confusion', 'dna.sequence', U, 'manipulate',
    'One strand reads A-T-G-C. What does the complementary strand read?',
    ['A-T-G-C', 'T-A-C-G', 'G-C-A-T'],
    1,
    'A pairs with T and C pairs with G, so each base is replaced by its partner.'),

  // ===== GEN-3 · alleles and phenotype =====================================
  c('gen3-allele-1', 'allele-definition', 'allele.pair', A, 'observe',
    'W and w sit at the same locus on two homologs. What are they?',
    ['Two different genes', 'Two alleles of one gene', 'Two chromosomes'],
    1,
    'Alleles are versions of the same gene found at the same locus.'),
  c('gen3-allele-2', 'allele-definition', 'allele.compare', A, 'manipulate',
    'How many copies of each autosomal gene does a body cell carry?',
    ['One', 'Two', 'Four'],
    1,
    'Body cells carry two copies, one inherited from each parent.'),
  c('gen3-allele-3', 'allele-definition', 'gene.locus', G7, 'observe',
    'Sample codes CH1-G1a and CH1-G1b come from the same locus. What does that tell you?',
    ['They are two versions of the same gene', 'They are from different chromosomes', 'They are the same allele'],
    0,
    'The shared locus means one gene; the different suffixes mean different versions.'),
  c('gen3-dominant-1', 'dominant-means-two', 'genotype.to.phenotype', A, 'predict',
    'A dragon carries one flame allele and one no-flame allele, and flame is dominant. What will it show?',
    ['Flame', 'No flame', 'A blend of both'],
    0,
    'A single dominant allele is enough to produce the dominant form.'),
  c('gen3-dominant-2', 'dominant-means-two', 'allele.pair', A, 'explain',
    'What does "dominant" describe?',
    ['How common the allele is in the population', 'Which form appears when the two alleles differ', 'How strong the dragon is'],
    1,
    'Dominance is about which form shows in a heterozygote, not about frequency or strength.'),
  c('gen3-recessive-1', 'recessive-disappears', 'genotype.to.phenotype', A, 'predict',
    'Two dragons showing the dominant form produce a hatchling showing the recessive form. How?',
    ['A new mutation must have occurred', 'Both parents carried a hidden recessive allele', 'The recessive form is not really recessive'],
    1,
    'Carriers hold a masked recessive allele that can be passed on and pair up.'),
  c('gen3-recessive-2', 'recessive-disappears', 'allele.pair', U, 'explain',
    'A masked recessive allele in a heterozygote is best described as:',
    ['Destroyed by the dominant allele', 'Still present and still heritable', 'Converted into the dominant allele'],
    1,
    'Masking affects what is visible, not whether the allele exists.'),
  c('gen3-geno-1', 'genotype-equals-phenotype', 'genotype.to.phenotype', A, 'explain',
    'Which genotypes can produce the dominant flame form?',
    ['Only the homozygous dominant', 'Homozygous dominant and heterozygous', 'Only the heterozygous'],
    1,
    'Two different genotypes give the same visible form, which is why appearance alone is weak evidence.'),
  c('gen3-geno-2', 'genotype-equals-phenotype', 'allele.compare', U, 'manipulate',
    'Two dragons look identical. What is the strongest next step to compare them?',
    ['Record their appearance more carefully', 'Sample and compare their alleles at the locus', 'Compare their trial scores'],
    1,
    'Only an allele record can distinguish identical-looking genotypes.'),

  // ===== GEN-4 · inheritance patterns ======================================
  c('gen4-onefrom-1', 'two-from-one-parent', 'gamete.select', A, 'observe',
    'How many alleles for one gene does each parent contribute to an offspring?',
    ['Both of its alleles', 'Exactly one', 'It depends on the parent’s sex'],
    1,
    'Each parent contributes one allele per gene, so the offspring ends with two.'),
  c('gen4-onefrom-2', 'two-from-one-parent', 'gamete.ploidy', A, 'explain',
    'An offspring has the allele pair Ww. Where did the two alleles come from?',
    ['Both from the mother', 'One from each parent', 'Both were made at fertilization'],
    1,
    'One allele arrives in the egg and one in the sperm.'),
  c('gen4-identical-1', 'identical-gametes', 'meiosis.stage', A, 'observe',
    'One parent produces four gametes. What is true of them?',
    ['They all carry the same alleles', 'They can carry different allele combinations', 'They each carry a full chromosome pair'],
    1,
    'Meiosis separates homologs differently into each gamete, so they differ.',
    'Watch which chromosome goes to which pole.'),
  c('gen4-identical-2', 'identical-gametes', 'gamete.select', A, 'explain',
    'Why can two hatchlings from the same parents look different?',
    ['Because the parents changed between clutches', 'Because different gametes carry different allele combinations', 'Because one was raised differently'],
    1,
    'Variation among gametes is the source of sibling variation.'),
  c('gen4-ploidy-1', 'gamete-stays-diploid', 'gamete.ploidy', A, 'observe',
    'A dragon body cell carries 5 chromosome pairs. How many chromosomes does one gamete carry?',
    ['10', '5', '20'],
    1,
    'A gamete carries one chromosome from each pair — half the body-cell number.'),
  c('gen4-ploidy-2', 'gamete-stays-diploid', 'meiosis.stage', U, 'explain',
    'What would happen if gametes kept the full chromosome pair count?',
    ['Nothing — that is normal', 'The chromosome number would double every generation', 'The offspring would be identical to its parent'],
    1,
    'Halving in meiosis is what keeps the chromosome number stable across generations.'),
  c('gen4-ratio-1', 'genotype-phenotype-ratio', 'cross.predict', U, 'predict',
    'A Ww × Ww cross gives which genotype ratio?',
    ['3:1', '1:2:1', '1:1'],
    1,
    'Genotypes come out 1 WW : 2 Ww : 1 ww, while the phenotype ratio is 3:1.'),
  c('gen4-ratio-2', 'genotype-phenotype-ratio', 'offspring.ratio', U, 'explain',
    'Why do the genotype and phenotype ratios of Ww × Ww differ?',
    ['Because the grid was filled in wrongly', 'Because WW and Ww look the same', 'Because ww is lethal'],
    1,
    'Two genotypes share one visible form, collapsing 1:2:1 into 3:1.'),
  c('gen4-count-1', 'punnett-count-error', 'cross.predict', A, 'observe',
    'What does each cell of a four-cell Punnett square represent?',
    ['One offspring that will be born', 'One equally likely allele combination', 'One parent'],
    1,
    'Each cell is a possible combination with equal probability, not a scheduled birth.'),
  c('gen4-count-2', 'punnett-count-error', 'offspring.ratio', A, 'predict',
    'A cross predicts 3:1. A clutch of 4 hatches 4 dominant. What is wrong?',
    ['The prediction was wrong', 'Nothing — small samples vary around the prediction', 'The parents were mislabelled'],
    1,
    'Four births is a small sample; departures from the ratio are expected.'),
  c('gen4-grid-1', 'grid-equals-family', 'cross.predict', A, 'explain',
    'A Punnett square is best described as:',
    ['A list of the offspring a pair will have', 'A probability model for each birth', 'A family tree'],
    1,
    'The grid gives the chance of each outcome at every birth, independently.'),
  c('gen4-prob-1', 'probability-guarantee', 'offspring.ratio', A, 'predict',
    'A pair has a 3:1 expectation. Their first three hatchlings all show the recessive form. What is the chance the fourth shows the dominant form?',
    ['100% — the ratio must balance out', '75% — each birth is independent', '25% — the pattern will continue'],
    1,
    'Each birth is independent, so earlier outcomes do not change the next probability.',
    'Ask whether the eggs know about each other.'),
  c('gen4-prob-2', 'probability-guarantee', 'offspring.sample', A, 'explain',
    'What does a 3:1 prediction actually promise?',
    ['Exactly three of every four offspring', 'A long-run tendency across many births', 'That the fourth offspring is always recessive'],
    1,
    'Ratios describe tendencies over many trials, never a guarantee for a specific clutch.'),
  c('gen4-sample-1', 'sample-size-irrelevant', 'offspring.sample', A, 'manipulate',
    'You want to test a 3:1 prediction. Which sample gives the clearer test?',
    ['A clutch of 4', 'A batch of 200', 'Either one works equally well'],
    1,
    'Larger samples sit closer to the predicted ratio, so departures become meaningful.'),
  c('gen4-sample-2', 'sample-size-irrelevant', 'offspring.ratio', U, 'explain',
    'As batch size grows, what happens to the observed ratio?',
    ['It drifts further from the prediction', 'It settles closer to the prediction', 'It stays exactly the same'],
    1,
    'More births average out the randomness of individual fertilizations.'),

  // ===== GEN-5 · pedigree evidence =========================================
  c('gen5-carrier-1', 'carrier-shows-trait', 'pedigree.carrier', A, 'observe',
    'What is a carrier?',
    ['An individual showing the recessive trait', 'An individual carrying a recessive allele without showing it', 'An individual with three alleles'],
    1,
    'A carrier is heterozygous: it holds the recessive allele but shows the dominant form.'),
  c('gen5-carrier-2', 'carrier-shows-trait', 'pedigree.trace', A, 'predict',
    'An unaffected dragon has an affected offspring with a recessive condition. What must be true of that parent?',
    ['It is a carrier', 'It is affected too', 'It contributed no allele'],
    0,
    'The affected offspring needed a recessive allele from each parent.'),
  c('gen5-skip-1', 'skipped-generation-impossible', 'pedigree.trace', A, 'explain',
    'A trait appears in generation I and again in generation III, but not II. What does that suggest?',
    ['The trait is dominant', 'The trait is recessive and generation II carried it', 'The pedigree is drawn incorrectly'],
    1,
    'Skipping a generation is the signature of a recessive trait passing through carriers.'),
  c('gen5-skip-2', 'skipped-generation-impossible', 'pedigree.carrier', U, 'explain',
    'Which pattern most strongly argues against a trait being dominant?',
    ['It appears in every generation', 'It disappears for a generation and returns', 'It appears only in males'],
    1,
    'A dominant trait cannot skip: showing it requires an allele from a parent who also showed it.'),
  c('gen5-symbol-1', 'pedigree-symbol-confusion', 'pedigree.trace', L, 'observe',
    'In a pedigree, what does a filled symbol indicate?',
    ['The individual is affected by the trait being traced', 'The individual is important to the line', 'The individual has been sequenced'],
    0,
    'Fill marks affected status; shape marks sex; lines mark relationship.'),
  c('gen5-budget-1', 'sequencing-replaces-reasoning', 'pedigree.sequence', U, 'manipulate',
    'You have budget to sequence two dragons out of nine. What is the best use of it?',
    ['Sequence the two with the clearest visible trait', 'Sequence the two whose genotype the pedigree cannot settle', 'Sequence at random to avoid bias'],
    1,
    'Sequencing is most informative where deduction has left genuine ambiguity.',
    'Work out who you can already name without a test.'),
  c('gen5-budget-2', 'sequencing-replaces-reasoning', 'pedigree.carrier', X, 'explain',
    'Why deduce carriers before spending sequencing budget?',
    ['Because sequencing is inaccurate', 'Because deduction narrows which tests would actually be informative', 'Because carriers cannot be sequenced'],
    1,
    'Reasoning identifies the informative tests; the budget then confirms them.'),

  // ===== GEN-6 · DNA and proteins ==========================================
  c('gen6-onegene-1', 'one-gene-one-trait', 'gene.to.trait', A, 'explain',
    'How does a gene contribute to a visible trait?',
    ['The gene is the trait', 'The gene codes for a protein, and proteins acting in cells produce the trait', 'The gene changes the dragon directly'],
    1,
    'There is always a protein step between a sequence and an observable trait.'),
  c('gen6-onegene-2', 'one-gene-one-trait', 'protein.product', U, 'explain',
    'A student says "the wings gene makes the wings." What is missing?',
    ['Nothing — that is accurate', 'The protein the gene codes for, and what that protein does in cells', 'The chromosome number'],
    1,
    'Naming the protein and its cellular effect is what completes the explanation.'),
  c('gen6-onegene-3', 'one-gene-one-trait', 'gene.to.trait', X, 'explain',
    'What does a model that zooms straight from gene to phenotype leave out?',
    ['Regulation, interactions, development, and environment', 'That chromosomes contain DNA', 'That alleles are gene versions'],
    0,
    'Phenotype depends on far more than one sequence, and the shortcut hides that.'),
  c('gen6-uracil-1', 'rna-uses-thymine', 'dna.transcribe', A, 'manipulate',
    'A DNA strand reads A-T-G. What does the messenger RNA copy read?',
    ['A-T-G', 'U-A-C', 'A-U-G'],
    2,
    'RNA substitutes uracil for thymine, so the transcript carries U instead of T.'),
  c('gen6-uracil-2', 'rna-uses-thymine', 'dna.transcribe', A, 'observe',
    'Which base appears in RNA but never in DNA?',
    ['Uracil', 'Thymine', 'Guanine'],
    0,
    'Uracil is the RNA-only base; thymine is the DNA-only base.'),
  c('gen6-replication-1', 'replication-destroys-template', 'dna.replicate', U, 'observe',
    'After replication, what has happened to the original DNA strands?',
    ['They were used up making the copy', 'They are preserved and each serves as a template', 'They were converted into RNA'],
    1,
    'Each original strand templates a new partner and remains intact.'),
  c('gen6-tvt-1', 'transcription-equals-translation', 'rna.translate', A, 'observe',
    'Which step produces a protein?',
    ['Transcription', 'Translation', 'Replication'],
    1,
    'Transcription makes RNA from DNA; translation reads RNA to build a protein.'),
  c('gen6-tvt-2', 'transcription-equals-translation', 'dna.transcribe', A, 'explain',
    'Put these in order: protein, DNA, messenger RNA.',
    ['DNA → messenger RNA → protein', 'Messenger RNA → DNA → protein', 'DNA → protein → messenger RNA'],
    0,
    'Information flows from DNA to RNA to protein.'),
  c('gen6-muttype-1', 'mutation-types-confused', 'dna.mutate', U, 'manipulate',
    'One base is swapped for another and the sequence length is unchanged. What kind of change is that?',
    ['A deletion', 'A substitution', 'An insertion'],
    1,
    'Substitutions exchange a base; insertions and deletions change the length.'),
  c('gen6-muttype-2', 'mutation-types-confused', 'dna.sequence', X, 'predict',
    'Which change is most likely to disrupt every codon after its position?',
    ['A substitution', 'An insertion of one base', 'A change in packing'],
    1,
    'Adding or removing a base shifts the reading frame for everything downstream.'),
  c('gen6-mutharm-1', 'mutation-always-harmful', 'dna.mutate', A, 'predict',
    'A base change leaves the protein product unchanged. What does that show?',
    ['Mutations are always harmful', 'Some sequence changes have no effect on the product', 'The repair system failed'],
    1,
    'Changes can be harmful, neutral, or occasionally useful.'),
  c('gen6-mutharm-2', 'mutation-always-harmful', 'protein.product', U, 'explain',
    'Why can two different DNA sequences produce the same protein?',
    ['Because DNA does not determine protein', 'Because more than one codon can specify the same amino acid', 'Because the ribosome corrects errors'],
    1,
    'Several codons map to the same amino acid, so some changes are silent.'),
  c('gen6-repair-1', 'repair-guarantees-no-mutations', 'dna.repair', X, 'explain',
    'A cell has working repair machinery. What follows?',
    ['It can never keep a mutation', 'Its error rate is lowered but not zero', 'Its DNA never changes'],
    1,
    'Repair reduces errors; some changes still persist.'),
  c('gen6-percent-1', 'percent-difference-error', 'allele.compare', X, 'manipulate',
    'Sequence A differs from B at 3 of 60 bases, and C differs from D at 4 of 200. Which pair is more similar?',
    ['A and B', 'C and D', 'They are equally similar'],
    1,
    'C and D differ at 2%, A and B at 5%; the count alone is misleading without the length.'),
  c('gen6-shape-1', 'protein-shape-irrelevant', 'protein.shape', U, 'predict',
    'Why does a protein’s folded shape matter?',
    ['It does not — only the amino acid list matters', 'Shape determines what the protein can bind to', 'Shape sets how fast it is made'],
    1,
    'Binding depends on complementary shape, which is how a protein does its job.'),
  c('gen6-shape-2', 'protein-shape-irrelevant', 'enzyme.substrate', U, 'manipulate',
    'An enzyme’s active site no longer fits its substrate. What is the most likely consequence?',
    ['The reaction it helps slows or stops', 'The substrate changes shape to fit', 'The enzyme is used up'],
    0,
    'A mismatched active site cannot bind, so the reaction is not helped along.'),

  // ===== GEN-7 · multiple alleles ==========================================
  c('gen7-max-1', 'two-alleles-max', 'multiple.alleles', A, 'observe',
    'A blood gene has four different alleles in the population. How many can one dragon carry?',
    ['All four', 'Two', 'One'],
    1,
    'A population can hold many alleles; an individual carries two copies of the gene.'),
  c('gen7-max-2', 'two-alleles-max', 'antiserum.test', A, 'explain',
    'Antiserum testing reveals more than two blood forms in a herd. What does that show?',
    ['The tests are unreliable', 'This gene has more than two alleles in the population', 'Some dragons have extra chromosomes'],
    1,
    'More than two forms across individuals means multiple alleles at that locus.'),
  c('gen7-codom-1', 'codominance-vs-incomplete', 'genotype.to.phenotype', U, 'observe',
    'A heterozygote shows both parental forms at once, side by side. What is that?',
    ['Incomplete dominance', 'Codominance', 'Complete dominance'],
    1,
    'Codominance shows both forms; incomplete dominance blends them into an intermediate.'),
  c('gen7-codom-2', 'codominance-vs-incomplete', 'multiple.alleles', U, 'predict',
    'A red and a white parent produce all pink offspring. Which pattern is that?',
    ['Codominance', 'Incomplete dominance', 'Multiple alleles'],
    1,
    'A blended intermediate is the signature of incomplete dominance.'),
  c('gen7-donor-1', 'universal-donor-confusion', 'donor.compatibility', A, 'predict',
    'A donor was compatible with one patient. What does that tell you about the next patient?',
    ['It will be compatible again', 'Compatibility depends on the new recipient’s markers', 'It will never be compatible again'],
    1,
    'Compatibility is a property of the donor–recipient pair, not of the donor alone.'),
  c('gen7-donor-2', 'universal-donor-confusion', 'antiserum.test', U, 'explain',
    'What determines whether a transfusion is safe?',
    ['The donor’s blood type alone', 'Which markers the recipient can react against', 'The volume available'],
    1,
    'The recipient’s possible reactions decide safety.'),

  // ===== GEN-8 · population diversity ======================================
  c('gen8-diversity-1', 'phenotype-equals-diversity', 'population.scan', A, 'observe',
    'An island population shows many colours but a genotype scan finds few alleles. What is true?',
    ['Visible variety proves genetic diversity', 'A varied-looking population can still be genetically narrow', 'The scan must be wrong'],
    1,
    'Appearance and allele richness are different measurements.'),
  c('gen8-diversity-2', 'phenotype-equals-diversity', 'population.metric', A, 'manipulate',
    'Which measurement best describes genetic diversity?',
    ['The number of visible forms', 'The number of distinct alleles carried', 'The number of dragons'],
    1,
    'Allele richness measures the genetic variety available to the population.'),
  c('gen8-freq-1', 'phenotype-frequency-equals-allele', 'population.metric', X, 'explain',
    'Why does counting dragons showing the dominant form under-count the recessive allele?',
    ['It does not', 'Because heterozygotes look dominant and hide a recessive allele', 'Because recessive alleles are rarer'],
    1,
    'Carriers are invisible to a phenotype count, so the allele is undercounted.'),
  c('gen8-metric-1', 'wrong-diversity-metric', 'population.metric', U, 'predict',
    'A population doubles in size but every new dragon descends from one pair. What happened to allele richness?',
    ['It doubled', 'It changed little or fell', 'It cannot be measured'],
    1,
    'Growth from a narrow source adds individuals without adding alleles.'),
  c('gen8-metric-2', 'wrong-diversity-metric', 'population.intervene', U, 'manipulate',
    'An island is declining and inbred. Which intervention most raises allele richness?',
    ['Breed the existing pairs more often', 'Relocate unrelated individuals into the island', 'Remove the weakest individuals'],
    1,
    'New unrelated individuals bring alleles the island does not already hold.'),
  c('gen8-best-1', 'best-with-best', 'selection.rationale', A, 'explain',
    'What is the risk of always breeding the top performer with the top performer?',
    ['There is no risk', 'The line loses allele variety and its ability to adapt', 'The offspring become too strong'],
    1,
    'Repeated narrow selection removes alleles the line may later need.'),
  c('gen8-best-2', 'best-with-best', 'population.metric', U, 'predict',
    'After several generations of strict selection, what usually happens to allele richness?',
    ['It rises', 'It falls', 'It stays constant'],
    1,
    'Selecting narrowly means fewer distinct alleles are passed on each generation.'),
  c('gen8-battle-1', 'battle-equals-mastery', 'trial.outcome', A, 'explain',
    'Your champion won its trial. What has that proven about your breeding decisions?',
    ['That they were correct', 'That this dragon beat this opponent once', 'That the alleles you selected are dominant'],
    1,
    'A trial is one measurement; it does not validate a breeding claim on its own.'),
  c('gen8-single-1', 'single-trial-causation', 'trial.outcome', U, 'explain',
    'How could you strengthen a claim that a trait caused better trial results?',
    ['Run the same trial again with the same dragon', 'Run trials across several dragons differing only in that trait', 'Choose a weaker opponent'],
    1,
    'Varying only the trait of interest across several subjects separates it from chance.'),
  c('gen8-stat-1', 'no-statistical-test', 'population.metric', X, 'explain',
    'Two groups differ by 4%. What is needed before calling that a finding?',
    ['Nothing — the numbers differ', 'A test of whether the difference exceeds expected variation', 'A larger arena'],
    1,
    'Differences must be weighed against the variation you would expect by chance.'),
  c('gen8-confound-1', 'confounded-comparison', 'population.scan', X, 'manipulate',
    'You compare two islands that differ in food supply, size, and allele richness. What can you conclude about allele richness?',
    ['That it caused the difference in survival', 'Very little, because several variables differ at once', 'That it is irrelevant'],
    1,
    'With several variables differing, no single one can be credited.'),
  c('gen8-unfair-1', 'unfair-comparison', 'trial.outcome', U, 'predict',
    'A well-fed dragon is matched against a starved one. What does the result measure?',
    ['Inherited advantage', 'The combined effect of condition and inheritance', 'Nothing at all'],
    1,
    'Unequal starting conditions confound whatever the trial was meant to test.'),
  c('gen8-model-1', 'model-is-universal', 'genome.hierarchy', X, 'explain',
    'This laboratory models four traits as simple dominant/recessive pairs. What limitation matters most?',
    ['Real traits often involve many genes and environmental effects', 'Chromosomes are not really in the nucleus', 'Alleles are not really gene versions'],
    0,
    'The simplification is useful for learning and misleading if mistaken for the general case.'),
];

const BY_ID = new Map(DRAGON_INQUIRY_BANK.map((item) => [item.id, item]));

export function inquiryItem(id: string | null | undefined): InquiryItem | null {
  return id ? (BY_ID.get(id) ?? null) : null;
}

export function itemsForConcept(conceptId: ConceptId): readonly InquiryItem[] {
  return DRAGON_INQUIRY_BANK.filter((item) => item.conceptId === conceptId);
}

/**
 * Concepts with no authored item at a given band. This is the coverage report that replaces
 * generated filler: a gap is reported rather than papered over.
 */
export function uncoveredConcepts(level: InstructionLevel): readonly ConceptId[] {
  const covered = new Set(
    DRAGON_INQUIRY_BANK.filter((item) => item.gradeBands.includes(level)).map(
      (item) => item.conceptId,
    ),
  );
  return DRAGON_CONCEPTS.filter(
    (concept) => concept.gradeBands.includes(level) && !covered.has(concept.id),
  ).map((concept) => concept.id);
}

export function assertValidInquiryBank(): void {
  const seen = new Set<string>();
  for (const item of DRAGON_INQUIRY_BANK) {
    if (seen.has(item.id)) throw new Error(`Duplicate inquiry item ${item.id}.`);
    seen.add(item.id);
    const concept = dragonConcept(item.conceptId);
    if (!concept) throw new Error(`Item ${item.id} targets unknown concept ${item.conceptId}.`);
    if (!concept.probes.includes(item.requiresProbe)) {
      throw new Error(
        `Item ${item.id} requires probe ${item.requiresProbe}, which concept ${concept.id} does not admit.`,
      );
    }
    if (!instrumentsWithProbe(item.requiresProbe).length) {
      throw new Error(`Item ${item.id} requires probe ${item.requiresProbe}, which no instrument declares.`);
    }
    if (!item.gradeBands.length) throw new Error(`Item ${item.id} declares no grade band.`);
    for (const band of item.gradeBands) {
      if (!concept.gradeBands.includes(band)) {
        throw new Error(`Item ${item.id} targets band ${band} outside concept ${concept.id}.`);
      }
    }
    if (item.kind === 'choice') {
      if (item.options.length < 2) throw new Error(`Item ${item.id} needs at least two options.`);
      if (!item.options.some((option) => option.id === item.correctOptionId)) {
        throw new Error(`Item ${item.id} has no option matching its correct id.`);
      }
    }
  }
}

assertValidInquiryBank();
